=== fannithm/spec/map-schema-v2-sekai.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Fannithm Map JSON v2-alpha.4 for Sekai Mode",
  "type": "object",
  "$defs": {
    "uuid": {
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    },
    "beatInteger": {
      "type": "integer",
      "minimum": 0
    },
    "beatNumerator": {
      "type": "integer",
      "minimum": 0
    },
    "beatDenominator": {
      "type": "integer",
      "minimum": 1
    },
    "beat": {
      "type": "object",
      "properties": {
        "integer": {
          "$ref": "#/$defs/beatInteger"
        },
        "numerator": {
          "$ref": "#/$defs/beatNumerator"
        },
        "denominator": {
          "$ref": "#/$defs/beatDenominator"
        }
      },
      "required": ["integer"],
      "additionalProperties": false,
      "dependentRequired": {
        "numerator": ["denominator"],
        "denominator": ["numerator"]
      }
    },
    "integerLane": {
      "type": "integer",
      "minimum": 0,
      "maximum": 11
    },
    "integerWidth": {
      "type": "integer",
      "minimum": 1,
      "maximum": 12
    },
    "timeline": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/uuid"
        },
        "name": {
          "type": "string"
        },
        "speed": {
          "type": "number",
          "$comment": "default value: 1"
        }
      },
      "required": ["id", "name"],
      "additionalProperties": false
    },
    "bpm": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/uuid"
        },
        "timeline": {
          "$ref": "#/$defs/uuid"
        },
        "beat": {
          "$ref": "#/$defs/beat"
        },
        "bpm": {
          "type": "number",
          "exclusiveMinimum": 0
        }
      },
      "required": ["id", "timeline", "beat", "bpm"],
      "additionalProperties": false
    },
    "flickDirection": {
      "type": "string",
      "enum": ["up", "left", "right"]
    },
    "noteType": {
      "type": "string",
      "enum": ["tap", "flick", "trace", "flick-trace"]
    },
    "note": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/uuid"
        },
        "timeline": {
          "$ref": "#/$defs/uuid"
        },
        "beat": {
          "$ref": "#/$defs/beat"
        },
        "type": {
          "$ref": "#/$defs/noteType"
        },
        "lane": {
          "$ref": "#/$defs/integerLane"
        },
        "width": {
          "$ref": "#/$defs/integerWidth"
        },
        "critical": {
          "type": "boolean"
        },
        "direction": {
          "$ref": "#/$defs/flickDirection"
        }
      },
      "required": ["id", "timeline", "beat", "type", "lane", "width"],
      "additionalProperties": false,
      "if": {
        "type": "object",
        "properties": {
          "type": {
            "enum": ["flick", "flick-trace"]
          }
        }
      },
      "then": {
        "required": ["direction"]
      },
      "else": {
        "properties": {
          "direction": false
        }
      }
    },
    "slideNodeType": {
      "type": "string",
      "enum": ["start", "invisible", "visible", "end", "flick-end"]
    },
    "curveType": {
      "type": "string",
      "enum": [
        "none",
        "linear",
        "ease-in",
        "ease-out",
        "ease-in-out",
        "cubic-bezier"
      ]
    },
    "cubicBezierValue": {
      "type": "number",
      "minimum": 0,
      "maximum": 1
    },
    "cubicBezier": {
      "type": "object",
      "properties": {
        "x1": {
          "$ref": "#/$defs/cubicBezierValue"
        },
        "y1": {
          "$ref": "#/$defs/cubicBezierValue"
        },
        "x2": {
          "$ref": "#/$defs/cubicBezierValue"
        },
        "y2": {
          "$ref": "#/$defs/cubicBezierValue"
        }
      },
      "required": ["x1", "y1", "x2", "y2"],
      "additionalProperties": false
    },
    "slideNode": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/uuid"
        },
        "type": {
          "$ref": "#/$defs/slideNodeType"
        },
        "beat": {
          "$ref": "#/$defs/beat"
        },
        "lane": {
          "$ref": "#/$defs/integerLane"
        },
        "width": {
          "$ref": "#/$defs/integerWidth"
        },
        "curve": {
          "$ref": "#/$defs/curveType"
        },
        "bezier": {
          "$ref": "#/$defs/cubicBezier"
        },
        "critical": {
          "type": "boolean"
        },
        "direction": {
          "$ref": "#/$defs/flickDirection"
        }
      },
      "required": ["id", "type", "beat"],
      "additionalProperties": false,
      "allOf": [
        {
          "$comment": "make lane, width and curve optional for visible node",
          "if": {
            "type": "object",
            "properties": {
              "type": {
                "enum": ["visible"]
              }
            }
          },
          "then": {
            "$comment": "lane, width and curve is optional for visible note, but you must set all of them if needed",
            "dependentRequired": {
              "lane": ["width", "curve"],
              "width": ["lane", "curve"],
              "curve": ["lane", "width"]
            }
          },
          "else": {
            "required": ["lane", "width", "curve"]
          }
        },
        {
          "$comment": "add critical to end node",
          "if": {
            "type": "object",
            "properties": {
              "type": {
                "enum": ["end", "flick-end"]
              }
            }
          },
          "then": {
            "type": "object",
            "properties": {
              "curve": {
                "enum": ["none"]
              }
            }
          },
          "else": {
            "type": "object",
            "properties": {
              "critical": false
            }
          }
        },
        {
          "$comment": "add direction to flick-end node",
          "if": {
            "type": "object",
            "properties": {
              "type": {
                "enum": ["flick-end"]
              }
            }
          },
          "then": {
            "required": ["direction"]
          },
          "else": {
            "properties": {
              "direction": false
            }
          }
        },
        {
          "$comment": "make bezier required for bezier curve",
          "if": {
            "type": "object",
            "properties": {
              "curve": {
                "enum": ["cubic-bezier"]
              }
            },
            "required": ["curve"]
          },
          "then": {
            "type": "object",
            "required": ["bezier"]
          },
          "else": {
            "type": "object",
            "properties": {
              "bezier": false
            }
          }
        }
      ]
    },
    "slide": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/uuid"
        },
        "timeline": {
          "$ref": "#/$defs/uuid"
        },
        "critical": {
          "type": "boolean"
        },
        "nodes": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/slideNode"
          },
          "minItems": 2
        }
      },
      "required": ["id", "timeline", "nodes"],
      "additionalProperties": false
    },
    "slideDecorationColor": {
      "type": "string",
      "enum": ["green", "yellow"]
    },
    "slideDecorationNode": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/uuid"
        },
        "beat": {
          "$ref": "#/$defs/beat"
        },
        "lane": {
          "type": "number",
          "minimum": 0,
          "maximum": 11
        },
        "width": {
          "type": "number",
          "minimum": 0,
          "maximum": 12
        },
        "curve": {
          "$ref": "#/$defs/curveType"
        },
        "bezier": {
          "$ref": "#/$defs/cubicBezier"
        }
      },
      "required": ["id", "beat", "lane", "width", "curve"],
      "additionalProperties": false,
      "if": {
        "type": "object",
        "properties": {
          "curve": {
            "enum": ["cubic-bezier"]
          }
        }
      },
      "then": {
        "required": ["bezier"]
      },
      "else": {
        "properties": {
          "bezier": false
        }
      }
    },
    "slideDecoration": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/uuid"
        },
        "timeline": {
          "$ref": "#/$defs/uuid"
        },
        "color": {
          "$ref": "#/$defs/slideDecorationColor"
        },
        "nodes": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/slideDecorationNode"
          },
          "minItems": 2
        }
      },
      "required": ["id", "timeline", "color", "nodes"],
      "additionalProperties": false
    },
    "animation": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/uuid"
        },
        "target": {
          "$ref": "#/$defs/uuid"
        },
        "type": {
          "type": "string",
          "enum": ["speed"]
        },
        "beat": {
          "$ref": "#/$defs/beat"
        },
        "curve": {
          "$ref": "#/$defs/curveType"
        },
        "bezier": {
          "$ref": "#/$defs/cubicBezier"
        },
        "value": {
          "type": "number"
        }
      },
      "required": ["id", "target", "type", "beat", "curve", "value"],
      "additionalProperties": false,
      "if": {
        "type": "object",
        "properties": {
          "curve": {
            "enum": ["cubic-bezier"]
          }
        }
      },
      "then": {
        "required": ["bezier"]
      },
      "else": {
        "properties": {
          "bezier": false
        }
      }
    }
  },
  "properties": {
    "$schema": {
      "type": "string"
    },
    "$fannithm": {
      "type": "object",
      "properties": {
        "version": {
          "$comment": "The format version of the map file",
          "type": "string",
          "enum": ["v2"]
        },
        "mode": {
          "$comment": "The game mode of the map file",
          "type": "string",
          "enum": ["sekai"]
        },
        "offset": {
          "$comment": "The time offset of the map file (in second)",
          "type": "number"
        }
      },
      "required": ["version", "mode"],
      "additionalProperties": false
    },
    "timelines": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/timeline"
      },
      "minItems": 1
    },
    "bpms": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/bpm"
      },
      "minItems": 1
    },
    "notes": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/note"
      }
    },
    "slides": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/slide"
      }
    },
    "decorations": {
      "type": "object",
      "properties": {
        "slides": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/slideDecoration"
          }
        }
      }
    },
    "animations": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/animation"
      }
    }
  },
  "required": ["$fannithm", "timelines", "bpms"],
  "additionalProperties": false
}

=== fannithm/spec/map-example-sekai.json
{
  "$schema": "./map-schema-v2-sekai.json",
  "$fannithm": {
    "version": "v2",
    "mode": "sekai",
    "offset": 0
  },
  "timelines": [
    {
      "id": "dd3db744-e5a8-4dfb-be0b-d1676dfc51ee",
      "name": "Timeline 1",
      "speed": 1
    }
  ],
  "bpms": [
    {
      "id": "2b2fff30-de32-4f75-8446-fdcfb26199fd",
      "timeline": "dd3db744-e5a8-4dfb-be0b-d1676dfc51ee",
      "beat": {
        "integer": 0
      },
      "bpm": 120
    }
  ],
  "notes": [
    {
      "id": "6b3d281a-fd4a-4045-8780-faf460b48abb",
      "timeline": "dd3db744-e5a8-4dfb-be0b-d1676dfc51ee",
      "type": "tap",
      "beat": {
        "integer": 1,
        "numerator": 1,
        "denominator": 2
      },
      "lane": 0,
      "width": 3
    },
    {
      "id": "a59415a4-db3e-4ea7-baf6-2fa67e5979dd",
      "timeline": "dd3db744-e5a8-4dfb-be0b-d1676dfc51ee",
      "type": "trace",
      "beat": {
        "integer": 1,
        "numerator": 1,
        "denominator": 2
      },
      "lane": 9,
      "width": 3
    },
    {
      "id": "ce7f116f-b982-41d8-b2ab-25664420bae5",
      "timeline": "dd3db744-e5a8-4dfb-be0b-d1676dfc51ee",
      "type": "flick-trace",
      "beat": {
        "integer": 2
      },
      "lane": 0,
      "width": 12,
      "direction": "up",
      "critical": true
    }
  ],
  "slides": [
    {
      "id": "30f079d7-1413-4a6f-aa38-69d2e2a6700e",
      "timeline": "dd3db744-e5a8-4dfb-be0b-d1676dfc51ee",
      "critical": true,
      "nodes": [
        {
          "id": "4853a8c1-94f3-42f5-a60c-eaddd20701d2",
          "type": "start",
          "beat": {
            "integer": 3
          },
          "lane": 0,
          "width": 3,
          "curve": "cubic-bezier",
          "bezier": {
            "x1": 0,
            "y1": 0,
            "x2": 1,
            "y2": 1
          }
        },
        {
          "id": "8d78494d-f947-4779-b939-8a0a4be198a0",
          "type": "visible",
          "beat": {
            "integer": 4
          }
        },
        {
          "id": "8d78494d-f947-4779-b939-8a0a4be198a0",
          "type": "invisible",
          "beat": {
            "integer": 4
          },
          "lane": 0,
          "width": 6,
          "curve": "ease-out"
        },
        {
          "id": "4e3670f0-890a-4b6c-8f9d-8b6b8f320d48",
          "type": "flick-end",
          "beat": {
            "integer": 5
          },
          "lane": 0,
          "width": 3,
          "curve": "none",
          "direction": "up"
        }
      ]
    }
  ],
  "animations": [
    {
      "id": "56bb55b9-1eb4-48cd-85f4-6588f560bb24",
      "target": "dd3db744-e5a8-4dfb-be0b-d1676dfc51ee",
      "type": "speed",
      "beat": {
        "integer": 0
      },
      "curve": "linear",
      "value": 1
    },
    {
      "id": "5136a618-2634-4ff2-9171-1d15735b1786",
      "target": "dd3db744-e5a8-4dfb-be0b-d1676dfc51ee",
      "type": "speed",
      "beat": {
        "integer": 1
      },
      "value": 1,
      "curve": "none"
    }
  ],
  "decorations": {
    "slides": [
      {
        "id": "e6526578-7222-40ec-a902-d8c8cce5edc3",
        "timeline": "dd3db744-e5a8-4dfb-be0b-d1676dfc51ee",
        "color": "green",
        "nodes": [
          {
            "id": "f90517e4-8dcc-4158-b55b-787b7bd1180f",
            "beat": {
              "integer": 6
            },
            "lane": 0,
            "width": 12,
            "curve": "ease-in"
          },
          {
            "id": "c13bf443-1faa-474b-86ef-6236d9891632",
            "beat": {
              "integer": 8
            },
            "lane": 0,
            "width": 2,
            "curve": "none"
          }
        ]
      },
      {
        "id": "063e2399-f3c3-40b0-88ec-c60dda0701fb",
        "timeline": "dd3db744-e5a8-4dfb-be0b-d1676dfc51ee",
        "color": "yellow",
        "nodes": [
          {
            "id": "f90517e4-8dcc-4158-b55b-787b7bd1180f",
            "beat": {
              "integer": 6
            },
            "lane": 0,
            "width": 12,
            "curve": "ease-in"
          },
          {
            "id": "c13bf443-1faa-474b-86ef-6236d9891632",
            "beat": {
              "integer": 8
            },
            "lane": 10,
            "width": 2,
            "curve": "none"
          }
        ]
      }
    ]
  }
}
